### ISSUE TITLE
Alternative Impulse Response

### ISSUE THREAD

**Issue by jeffshee** [m4tx/thinkpad-p14s-g4-linux#1]
There are impulse response presets created on a P14s G4 AMD running Windows 11. They may provide better audio quality compared to the current T14s G3 convolver configs.

https://stuff.kurz.pw/arch/P14s_G4/Speakers/

Source: https://wiki.archlinux.org/title/Lenovo_ThinkPad_T14_(AMD)_Gen_4

Would you be interested in evaluating these presets for possible inclusion in the repository?

**Comment by m4tx** [comment]
I've checked them and indeed they sound nicer than the old EasyEffect preset, even without the additional effects added. Thanks a lot for that, I've added them to the repo!
